version: "3"
services:
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./content/index.php:/var/www/homework/index.php
      - ./config/application.local.conf:/etc/nginx/sites-enabled/application.local.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=application.local
      - NGINX_PORT=80
    networks:
      - homework



  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    image: php-fpm
    container_name: php-fpm
    volumes:
        - ./content/index.php:/var/www/homework/index.php
    networks:
      - homework


  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - homework


  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - homework
    environment:
      - MEMCACHED_MAX_CONNECTIONS=100
      - MEMCACHED_THREADS=1


  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "5000:5000"
    networks:
      - homework
  
networks:
  homework:
    driver: bridge